version: "3"

services:
  doccano:
    image: chakkiworks/doccano
    platform: linux/amd64
    ports:
      - "8000:8000"
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@example.com
      - ADMIN_PASSWORD=password
    
  postgres:
    image: postgres:10-alpine
    platform: linux/amd64
    environment:
      - POSTGRES_USER=doccano
      - POSTGRES_PASSWORD=doccano
      - POSTGRES_DB=doccano
    volumes:
      - postgres-data:/var/lib/postgresql/data
